import { Injectable, inject } from '@angular/core';
import { HashedFile, HashingService } from './hashing.service';

export interface ManifestInput {
    title: string;
    version: string;
    license: string;
    authorGivenNames: string;
    authorFamilyNames: string;
    authorEmail: string;
    files: HashedFile[];
}

export interface BuiltManifest {
    /** YAML text in CITATION.cff 1.2.0 format. */
    yaml: string;
    /** SHA-256 of the YAML — this is what gets timestamped on Bitcoin. */
    sha256: string;
    /** ISO timestamp at which the manifest was issued (local clock). */
    issuedAt: string;
}

/**
 * Builds a CITATION.cff manifest from user input + hashed files,
 * then computes the master SHA-256 of the manifest itself.
 *
 * The master hash is what we will eventually submit to OpenTimestamps
 * for Bitcoin anchoring. Until then it serves as the "deposit fingerprint".
 */
@Injectable({ providedIn: 'root' })
export class ManifestService {
    private readonly hashing = inject(HashingService);

    async build(input: ManifestInput): Promise<BuiltManifest> {
        const issuedAt = new Date().toISOString();
        const yaml = renderCff(input, issuedAt);
        const sha256 = await this.hashing.hashString(yaml);
        return { yaml, sha256, issuedAt };
    }
}

function renderCff(input: ManifestInput, issuedAt: string): string {
    const dateReleased = issuedAt.slice(0, 10);
    const lines: string[] = [];

    lines.push('# CITATION.cff — generated by mayday.software');
    lines.push('# Cryptographic copyright deposit manifest. SHA-256 of this');
    lines.push('# file is the fingerprint that should be anchored in Bitcoin');
    lines.push('# via OpenTimestamps to prove existence as of a specific block.');
    lines.push('cff-version: 1.2.0');
    lines.push('message: "If you reference this work, please cite it using the metadata in this file."');
    lines.push(`title: ${yamlString(input.title)}`);
    lines.push('type: software');
    lines.push(`version: ${yamlString(input.version)}`);
    lines.push(`date-released: "${dateReleased}"`);
    lines.push(`license: ${yamlString(input.license)}`);
    lines.push('authors:');
    lines.push(`  - given-names: ${yamlString(input.authorGivenNames)}`);
    if (input.authorFamilyNames) {
        lines.push(`    family-names: ${yamlString(input.authorFamilyNames)}`);
    }
    if (input.authorEmail) {
        lines.push(`    email: ${yamlString(input.authorEmail)}`);
    }
    lines.push(`issued-at: "${issuedAt}"`);
    lines.push(`issued-by: "mayday.software"`);
    lines.push('files:');
    for (const f of input.files) {
        lines.push(`  - path: ${yamlString(f.path)}`);
        lines.push(`    size: ${f.size}`);
        lines.push(`    sha256: "${f.sha256}"`);
    }
    lines.push('');
    return lines.join('\n');
}

function yamlString(value: string): string {
    // Simple safe quoting — wrap in double quotes and escape backslash + quote.
    const escaped = (value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
}
